server:
  port: 8080

spring:
  application:
    name: mini-weverse-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: chat-service-ws
              uri: ${CHAT_SERVICE_WS_URL:ws://localhost:8082}
              predicates:
                - Path=/api/chat/ws-chat
            - id: chat-service
              uri: ${CHAT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/chat/**
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/notifications/**
            - id: community-service
              uri: ${COMMUNITY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/**

jwt:
  public-key-path: keys/public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST:zipkin}:9411/api/v2/spans
