spring:
  application:
    name: mini-weverse
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  private-key-path: keys/private.pem
  public-key-path: keys/public.pem
  access-token-validity: 1800000
  refresh-token-validity: 1209600000
